import rejectionResponse from './rejection';

export default (response, status) => {

// handles the callback generated by PubNub grants

  if (!status.message || status.message !== 'Success') {
      return rejectionResponse(403, 'Invalid Grant');
  }

  return response.send(200);
}
